"""Pydantic v2 validation schemas for Sales MIS API.

Implements strict data transfer objects (DTOs) with field validations,
custom validators for business rules, and nested response schemas for MIS KPIs.
"""

import datetime as dt
from typing import Optional, List
from pydantic import BaseModel, Field, ConfigDict, field_validator


class SaleBase(BaseModel):
    """Base schema defining common sales attributes and validation rules."""

    date: dt.date = Field(..., description="Date of the sale (cannot be in the future)")
    region: str = Field(..., min_length=2, max_length=50, description="Geographic sales region")
    product: str = Field(..., min_length=1, max_length=100, description="Product name or SKU")
    quantity: int = Field(..., gt=0, description="Number of units sold (must be > 0)")
    unit_price: float = Field(..., gt=0.0, description="Unit price in currency (must be > 0)")
    salesperson: str = Field(..., min_length=1, max_length=100, description="Name of salesperson")

    @field_validator("date")
    @classmethod
    def validate_date_not_in_future(cls, v: dt.date) -> dt.date:
        """Ensure the sales transaction date is not set in the future."""
        if v > dt.date.today():
            raise ValueError("Sale date cannot be in the future")
        return v

    @field_validator("region", "product", "salesperson")
    @classmethod
    def validate_strip_whitespace(cls, v: str) -> str:
        """Strip surrounding whitespace and ensure string is not empty."""
        cleaned = v.strip()
        if not cleaned:
            raise ValueError("Field cannot be empty or only whitespace")
        return cleaned


class SaleCreate(SaleBase):
    """Schema for creating a new sales transaction."""

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "date": "2026-03-10",
                "region": "North",
                "product": "Enterprise Cloud Suite",
                "quantity": 5,
                "unit_price": 1200.0,
                "salesperson": "Jane Doe",
            }
        }
    )


class SaleUpdate(BaseModel):
    """Schema for updating an existing sales transaction (all fields optional)."""

    date: Optional[dt.date] = Field(None, description="Updated sale date")
    region: Optional[str] = Field(None, min_length=2, max_length=50)
    product: Optional[str] = Field(None, min_length=1, max_length=100)
    quantity: Optional[int] = Field(None, gt=0)
    unit_price: Optional[float] = Field(None, gt=0.0)
    salesperson: Optional[str] = Field(None, min_length=1, max_length=100)

    @field_validator("date")
    @classmethod
    def validate_date_not_in_future(cls, v: Optional[dt.date]) -> Optional[dt.date]:
        """Ensure date is not in future if provided."""
        if v is not None and v > dt.date.today():
            raise ValueError("Sale date cannot be in the future")
        return v

    @field_validator("region", "product", "salesperson")
    @classmethod
    def validate_strip_whitespace(cls, v: Optional[str]) -> Optional[str]:
        """Strip whitespace if value is provided."""
        if v is not None:
            cleaned = v.strip()
            if not cleaned:
                raise ValueError("Field cannot be empty or only whitespace")
            return cleaned
        return v


class SaleResponse(SaleBase):
    """Schema for returning a single sales transaction with computed fields."""

    id: int = Field(..., description="Unique database identifier")
    revenue: float = Field(..., description="Total computed revenue (quantity * unit_price)")
    created_at: dt.datetime = Field(..., description="Record creation timestamp")
    updated_at: dt.datetime = Field(..., description="Record last updated timestamp")

    model_config = ConfigDict(from_attributes=True)


class RegionSummary(BaseModel):
    """Aggregated sales performance per geographic region."""

    region: str = Field(..., description="Geographic region name")
    total_revenue: float = Field(..., description="Total revenue generated in region")
    total_units: int = Field(..., description="Total quantity of items sold in region")
    transaction_count: int = Field(..., description="Number of sales transactions")
    percentage_of_total: float = Field(..., description="Share of total revenue as percentage")


class ProductSummary(BaseModel):
    """Summary metrics for top-performing product."""

    product: str = Field(..., description="Product name")
    total_revenue: float = Field(..., description="Total revenue generated by product")
    total_units: int = Field(..., description="Total units sold")
    transaction_count: int = Field(..., description="Number of transactions")


class MonthlyGrowthSummary(BaseModel):
    """Month-over-month revenue and growth analytics."""

    month: str = Field(..., description="Calendar month in YYYY-MM format")
    revenue: float = Field(..., description="Total revenue in the month")
    units_sold: int = Field(..., description="Total units sold in the month")
    growth_percentage: Optional[float] = Field(
        None,
        description="Month-over-month growth percentage compared to preceding month",
    )


class SalesSummaryResponse(BaseModel):
    """Comprehensive executive MIS KPI summary response."""

    total_revenue: float = Field(..., description="Total revenue across all sales")
    total_units_sold: int = Field(..., description="Total units sold across all transactions")
    total_transactions: int = Field(..., description="Total number of completed sales records")
    average_order_value: float = Field(..., description="Average revenue per transaction")
    revenue_by_region: List[RegionSummary] = Field(..., description="Breakdown of sales by region")
    top_selling_product: Optional[ProductSummary] = Field(None, description="Product generating highest revenue")
    monthly_growth: List[MonthlyGrowthSummary] = Field(..., description="Monthly trend and MoM growth rates")
