"""Base repository providing generic CRUD operations.

Demonstrates OOP Abstraction and Generics: decouples database persistence
mechanics from concrete domain entities.
"""

from typing import Generic, TypeVar, Type, Optional, List
from sqlalchemy.orm import Session
from sqlalchemy import select

ModelType = TypeVar("ModelType")


class BaseRepository(Generic[ModelType]):
    """Generic repository implementing standard CRUD data access patterns.

    Attributes:
        db (Session): Active SQLAlchemy database session.
        model (Type[ModelType]): SQLAlchemy model class being managed.
    """

    def __init__(self, db: Session, model: Type[ModelType]) -> None:
        """Initialize repository with session and entity model class."""
        self._db = db
        self._model = model

    @property
    def db(self) -> Session:
        """Expose current database session for subclasses."""
        return self._db

    @property
    def model(self) -> Type[ModelType]:
        """Expose entity model class."""
        return self._model

    def get_by_id(self, entity_id: int) -> Optional[ModelType]:
        """Retrieve a single entity by its primary key ID.

        Args:
            entity_id (int): Primary key identifier.

        Returns:
            Optional[ModelType]: Found entity or None.
        """
        stmt = select(self._model).where(self._model.id == entity_id)
        return self._db.scalars(stmt).first()

    def list_all(self, skip: int = 0, limit: int = 100) -> List[ModelType]:
        """Retrieve a paginated list of all entities.

        Args:
            skip (int): Number of records to bypass.
            limit (int): Maximum records to return.

        Returns:
            List[ModelType]: Collection of entities.
        """
        stmt = select(self._model).offset(skip).limit(limit)
        return list(self._db.scalars(stmt).all())

    def create(self, entity: ModelType) -> ModelType:
        """Persist a new entity instance to the database.

        Args:
            entity (ModelType): New entity instance.

        Returns:
            ModelType: Persisted entity with autogenerated fields populated.
        """
        self._db.add(entity)
        self._db.commit()
        self._db.refresh(entity)
        return entity

    def update(self, entity: ModelType) -> ModelType:
        """Commit updates to an existing entity instance.

        Args:
            entity (ModelType): Modified entity instance.

        Returns:
            ModelType: Refreshed entity instance.
        """
        self._db.commit()
        self._db.refresh(entity)
        return entity

    def delete(self, entity: ModelType) -> None:
        """Remove an entity instance from the database.

        Args:
            entity (ModelType): Entity instance to delete.
        """
        self._db.delete(entity)
        self._db.commit()
